// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1SVKQAbqTWMouYwhDsgujyX2cOIJRjU',
    appId: '1:37837355921:web:b131300b4a1b5335393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    authDomain: 'explorer-ef6bc.firebaseapp.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjynqs5iDQ2iWyXIGfQ2lRBfKpbBLsvL4',
    appId: '1:37837355921:android:2b16848293faa1de393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    storageBucket: 'explorer-ef6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0q-gqIfYEQ_50hCaALqtLvrP4QnpLiDU',
    appId: '1:37837355921:ios:d78ad792a93f1251393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    storageBucket: 'explorer-ef6bc.appspot.com',
    iosBundleId: 'com.irent.irent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0q-gqIfYEQ_50hCaALqtLvrP4QnpLiDU',
    appId: '1:37837355921:ios:17a0be423dddc801393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    storageBucket: 'explorer-ef6bc.appspot.com',
    iosBundleId: 'com.irent.irent.RunnerTests',
  );
}
